version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-1
    DEBIAN_FRONTEND: noninteractive
    TZ: Asia/Tokyo

phases:
  # pre_build:

  build:
    commands:
      - apt-get update -y
      - apt-get install -y ruby python3 python3-dev
      - pip3 install awscli
      - mkdir tmp
      - gem install rubyzip
      - ruby app.rb
      - aws s3 sync ./tmp s3://tasuki-japanese-addresses

  # post_build:

# artifacts:
#   files:
#     - masked_db_dump.sql
