version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-1
    DEBIAN_FRONTEND: noninteractive
    TZ: Asia/Tokyo

phases:
  # pre_build:

  build:
    commands:
      - apt-get update -y
      - apt-get install -y ruby python3 python3-pip
      - pip3 isntall awscli
      - mkdir tmp
      - gem install rubyzip
      - ruby app.rb
      - aws s3 sync s3://tasuki-japanese-addresses/test tmp/

  # post_build:

# artifacts:
#   files:
#     - masked_db_dump.sql
